package com.karasiq.proxychecker.test.providers

import com.karasiq.proxychecker.providers.ProxyCheckerServicesProvider
import com.karasiq.proxychecker.providers.default.{DefaultActorSystemProvider, DefaultProxyCheckerMeasurerActorProvider, DefaultProxyCheckerMeasurerEventBusProvider, DefaultProxyListParserProvider}

trait TestServicesProvider extends ProxyCheckerServicesProvider with DefaultActorSystemProvider with DefaultProxyCheckerMeasurerEventBusProvider with DefaultProxyCheckerMeasurerActorProvider with DefaultProxyListParserProvider with TestGeoipResolverProvider with TestProxyStoreProvider with TestWebServiceCacheProvider with TestUpdateWatcherProvider with TestProxyListSchedulerProvider
